# fly.toml app configuration file generated for aye-captain on 2026-07-09T19:05:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aye-captain'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  UTTERANCE_LOG = '/data/utterances.jsonl'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
